services:
    database:
        ports:
            - '5332:5332'
        environment:
            - POSTGRES_PASSWORD=1234
        image: 'postgres'
        restart: always

    memcached:
      image: 'memcached'
      ports:
        - '11211:11211'
      restart: always

    webapp:
      build: .
      ports:
        - '80:5000'
        - '5000:5000'
      depends_on:
        - database
        - memcached
      restart: on-failure
